// Keep the original CET-6 assets unchanged so existing word IDs remain compatible.
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
global.window={};require('./app/assets/words.js');require('./app/assets/meanings.js');require('./app/assets/examples.js');
const csv=fs.readFileSync(path.join(__dirname,'tools/ecdict.csv'),'utf8');
const words=[],dailyCandidates=[],seen=new Set(),dailySeen=new Set();let headers=null,row=[],field='',quoted=false;
function consume(){row.push(field);field='';if(!headers){headers=row;row=[];return;}const r=Object.fromEntries(headers.map((h,i)=>[h,row[i]||'']));row=[];if(!r.translation||!/^[a-z][a-z '-]*$/i.test(r.word))return;const tags=r.tag.split(' '),key=r.word.toLowerCase(),w={w:r.word,p:r.phonetic,t:r.translation.replace(/\\n/g,'\n'),f:Number(r.bnc)||Number(r.frq)||0,basis:Number(r.bnc)?'BNC':Number(r.frq)?'FRQ':'none'};if(tags.includes('cet4')&&!seen.has(key)){seen.add(key);words.push({...w});}if(w.f>0&&w.f<=10000&&(!/^[A-Z]/.test(w.w)||w.w==='I')&&(r.oxford==='1'||tags.some(t=>['zk','gk','cet4','cet6'].includes(t)))&&!dailySeen.has(key)){dailySeen.add(key);dailyCandidates.push(w);}}
for(let i=0;i<csv.length;i++){const c=csv[i];if(c==='"'){if(quoted&&csv[i+1]==='"'){field+='"';i++;}else quoted=!quoted;}else if(c===','&&!quoted){row.push(field);field='';}else if(c==='\n'&&!quoted)consume();else if(c!=='\r')field+=c;}if(field||row.length)consume();
words.sort((a,b)=>(a.f||999999)-(b.f||999999)||a.w.localeCompare(b.w));
if(words.length<1000)throw Error('Unexpectedly small CET-4 source');
function concise(t){const chunks=[],posSeen=new Set();for(const line of t.split('\n')){if(/^\s*\[/.test(line))continue;const match=line.match(/^\s*(n|a|adj|v|vt|vi|adv|ad|prep|conj|pron|num|interj|pl|abbr|art)\.\s*(.+)$/i);if(!match)continue;let pos=match[1].toLowerCase();if(['v','vt','vi'].includes(pos))pos='v';if(pos==='a')pos='adj';if(pos==='ad')pos='adv';if(posSeen.has(pos))continue;const senses=match[2].replace(/\[[^\]]*\]/g,'').split(/[,，；;]/).map(s=>s.trim()).filter(s=>/[\u3400-\u9fff]/.test(s)&&s.length<=24).slice(0,2);if(senses.length){chunks.push(pos+'. '+senses.join('；'));posSeen.add(pos);}if(chunks.length>=3)break;}return chunks.length?chunks.join('；'):t.split('\n')[0].replace(/\[[^\]]*\]/g,'').split(/[,，；;]/).slice(0,2).join('；');}
const basic={the:'art. 这；那（表示特指）',be:'v. 是；存在',is:'v. 是（be 的现在时形式）',are:'v. 是（be 的现在时形式）',was:'v. 是（be 的过去时形式）',were:'v. 是（be 的过去时形式）',been:'v. 是；存在（be 的过去分词）',have:'v. 有；经历；aux. 构成完成时',has:'v. 有（have 的第三人称单数）；aux. 构成完成时',had:'v. 有（have 的过去式）；aux. 构成过去完成时',do:'v. 做；aux. 构成疑问或否定',does:'v. 做（do 的第三人称单数）；aux. 构成疑问或否定',did:'v. 做（do 的过去式）；aux. 构成疑问或否定',a:'art. 一个；一（用于辅音音素前）',an:'art. 一个；一（用于元音音素前）',as:'prep. 作为；conj. 当……时；因为；adv. 同样地',can:'aux. 能；可以',will:'aux. 将；愿意；n. 意愿',would:'aux. 将会；愿意（用于假设或委婉表达）',could:'aux. 能；可以（用于过去或委婉表达）',should:'aux. 应该',may:'aux. 可以；可能',might:'aux. 可能',must:'aux. 必须；一定',shall:'aux. 将；要',need:'v. 需要；n. 需要',that:'pron. 那；conj. 引导从句',this:'pron. 这；adj. 这个',it:'pron. 它',its:'pron. 它的',to:'prep. 向；到；表示不定式',of:'prep. ……的；属于',in:'prep. 在……里；在……期间',on:'prep. 在……上；在（某日）',for:'prep. 为了；给',at:'prep. 在（地点或时刻）',by:'prep. 由；通过；在……旁',with:'prep. 和；用',from:'prep. 从；来自',or:'conj. 或者；否则',but:'conj. 但是；prep. 除了',and:'conj. 和；并且',if:'conj. 如果；是否',not:'adv. 不；没有',so:'adv. 如此；conj. 因此',there:'adv. 在那里；表示存在',I:'pron. 我',i:'pron. 我',you:'pron. 你；你们',he:'pron. 他',she:'pron. 她',we:'pron. 我们',they:'pron. 他们；她们；它们',me:'pron. 我（宾格）',him:'pron. 他（宾格）',her:'pron. 她（宾格）；她的',us:'pron. 我们（宾格）',them:'pron. 他们；她们；它们（宾格）',my:'pron. 我的',your:'pron. 你的；你们的',his:'pron. 他的',our:'pron. 我们的',their:'pron. 他们的；她们的；它们的',no:'adj. 没有；adv. 不',yes:'adv. 是；对',get:'v. 得到；变得',make:'v. 制作；使',like:'v. 喜欢；prep. 像',well:'adv. 好；adj. 身体好的',back:'adv. 回到原处；n. 背部',right:'adj. 正确的；右边的；n. 权利',left:'adj. 左边的；v. leave 的过去式和过去分词',just:'adv. 刚刚；仅仅；adj. 公正的',one:'num. 一；pron. 一个（人或事物）',only:'adv. 仅仅；adj. 唯一的',all:'adj. 全部的；pron. 所有；adv. 完全',some:'adj. 一些；pron. 有些',more:'adj. 更多的；adv. 更',about:'prep. 关于；adv. 大约'};
const meanings={},examples={},reviewed=[];
dailyCandidates.sort((a,b)=>a.f-b.f||a.w.localeCompare(b.w));const daily=dailyCandidates.slice(0,1000);
if(daily.length!==1000)throw Error('Daily vocabulary incomplete');
for(const w of [...words,...daily]){meanings[w.w]=basic[w.w]||window.WORDLEAF_MEANINGS[w.w]||concise(w.t);if(basic[w.w]&&!reviewed.includes(w.w))reviewed.push(w.w);if(!meanings[w.w]||meanings[w.w].length>180)throw Error('Invalid Chinese meaning: '+w.w);if(window.WORDLEAF_EXAMPLES[w.w])examples[w.w]=window.WORDLEAF_EXAMPLES[w.w];delete w.t;}
function rank(list){list.forEach((w,i)=>{w.order=i+1;w.tier=i<1500?'common':i<3500?'intermediate':'extended';});return list;}
rank(words);rank(daily);
const extras={cet4:{label:'CET-4',title:'四级词库',mark:'4',dataset:'ecdict-cet4-v1',description:'ECDICT 四级标签词条，按通用语料参考顺序学习。',words,meanings:Object.fromEntries(words.map(w=>[w.w,meanings[w.w]])),examples:Object.fromEntries(words.filter(w=>examples[w.w]).map(w=>[w.w,examples[w.w]]))},daily:{label:'日常学习',title:'日常常用词',mark:'日',dataset:'ecdict-daily-v1',description:'从开放词典选取 1,000 个通用常用词，适合日常积累。',words:daily,meanings:Object.fromEntries(daily.map(w=>[w.w,meanings[w.w]])),examples:Object.fromEntries(daily.filter(w=>examples[w.w]).map(w=>[w.w,examples[w.w]]))}};
fs.writeFileSync(path.join(__dirname,'app/assets/modes.js'),'window.WORDLEAF_EXTRA_BOOKS='+JSON.stringify(extras)+';\n');
const audit={source:'https://github.com/skywind3000/ECDICT',sourceSHA256:crypto.createHash('sha256').update(csv).digest('hex'),cet4:words.length,daily:daily.length,dailySelection:'First 1,000 reference-ranked entries tagged zk, gk, cet4, cet6 or oxford; ranks 1..10,000 eligible; exclude initially capitalized words except I. General vocabulary, not a curated scenario course.',basicMeaningsReviewed:reviewed.length,basicReviewedWords:reviewed,meaningPolicy:'Reuse existing CET-6 primary meanings where available; otherwise use reviewed basic overrides or shortened source Chinese meanings. No English definitions shipped.',frequencyLimit:'BNC rank first, FRQ otherwise. Not exam frequencies or official complete syllabuses.'};
fs.writeFileSync(path.join(__dirname,'modes-source.json'),JSON.stringify(audit,null,2));
console.log(JSON.stringify({cet4:words.length,daily:daily.length,basicReviewed:reviewed.length,firstDaily:daily.slice(0,15).map(w=>({w:w.w,m:meanings[w.w]}))},null,2));
