async(page)=>{
  await page.goto('http://127.0.0.1:8765/');
  const checks=[],errors=[];page.on('pageerror',e=>errors.push(e.message));
  const assert=(ok,msg)=>{if(!ok)throw Error(msg);checks.push(msg);};
  const click=name=>page.getByRole('button',{name,exact:true}).click();
  const action=(a,id)=>page.locator(`[data-action="${a}"]${id?'[data-id="'+id+'"]':''}`).first().click();
  const read=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('wordleaf-state')));
  const saveFixture=async(s)=>{await page.goto('http://127.0.0.1:8765/qa-blank');await page.evaluate(s=>localStorage.setItem('wordleaf-state',JSON.stringify(s)),s);await page.goto('http://127.0.0.1:8765/');};
  const legacy=await page.evaluate(()=>{const d=new Date();d.setDate(d.getDate()-1);const key=dayKey(d),out=WORDS[2000].w;return{version:1,dataset:DATASET,goal:20,words:{government:{stage:2,due:Date.now()+DAY,reps:2,star:true,first:key,lapses:1},[out]:{stage:3,due:Date.now()+DAY,reps:3,star:true,first:key,lapses:0}},history:{[key]:{words:['government',out],new:['government',out],attempts:5}}};});
  const outside=Object.keys(legacy.words)[1];await saveFixture(legacy);
  await click('我的');await page.getByLabel('每天的新词目标').selectOption('5');
  let s=await read();assert(s.version===2&&s.words.government.stage===2&&s.words.government.reps===2&&s.words.government.star,'Upgrade migrates old progress and favorites');
  assert(s.words.government.meaningWeak&&s.words.government.mistakeAt===0,'Legacy forgotten words migrate without inventing an error date');
  assert(s.words[outside].reps===3&&Object.values(s.history)[0].attempts===5,'Upgrade preserves out-of-scope progress and daily history');
  await action('plan');await page.getByLabel('学习路线',{exact:true}).selectOption('focus');await page.getByLabel('本轮范围上限').selectOption('100');
  await page.getByLabel('备考天数').fill('7');await page.getByLabel('每天投入分钟').fill('5');
  assert((await page.locator('#plan-preview').innerText()).includes('超出所选天数'),'Plan preview explains when coverage exceeds the time horizon');
  await page.screenshot({path:'output/playwright/v1.1-plan.png'});await click('保存学习计划');
  s=await read();assert(s.plan.route==='focus'&&s.plan.ids.length===100&&s.goal===5,'Focus route stores a fixed limited vocabulary scope');
  assert(!s.plan.ids.includes(outside)&&s.words[outside].reps===3,'Changing scope preserves learned words outside the plan');
  await click('开始今日学习');assert(await page.getByRole('heading',{name:'system',exact:true}).count()===1,'Already learned words are excluded from the new-word queue');
  await click('这个词我已会，跳过');s=await read();assert(s.words.system.known&&Object.values(s.history).every(h=>!h.new.includes('system')),'Known-word skip does not consume the daily new-word quota');
  await click('撤销上一次选择');s=await read();assert(!s.words.system&&s.session.index===0&&s.session.queue.length===5,'Undo restores a skipped word and its queue');
  await click('这个词我已会，跳过');await click('查看释义');
  assert(await page.getByText('The library can provide useful information.',{exact:true}).count()===1,'The word card displays an offline contextual example');
  assert(await page.getByText('查看英文释义',{exact:true}).count()===0&&await page.getByText('展开完整中文释义',{exact:true}).count()===0,'Word cards only show concise Chinese meanings, without full or English glosses');
  assert(await page.evaluate(()=>WORDS.every(w=>!w.d&&!w.t)),'Runtime vocabulary does not contain the removed English or full glosses');
  assert(await page.evaluate(()=>shortMeaning(WORD_MAP.get('natural')).includes('自然')&&!shortMeaning(WORD_MAP.get('natural')).includes('白痴')),'Reviewed primary meanings avoid an obsolete first dictionary sense');
  assert(await page.getByText('图书馆可以提供有用的信息。',{exact:true}).isVisible()===false,'Example translation is folded until requested');
  await page.getByText('查看例句翻译',{exact:true}).click();assert(await page.getByText('图书馆可以提供有用的信息。',{exact:true}).isVisible(),'Example translation can be revealed');
  await page.screenshot({path:'output/playwright/v1.1-card.png'});
  await action('rate','again');s=await read();assert(s.words.provide.meaningWeak&&s.words.provide.lapses===1,'Forgotten meaning enters the dedicated reinforcement queue');
  await click('撤销上一次选择');s=await read();assert(!s.words.provide&&s.session.revealed&&s.session.queue.length===6,'Undo removes the mistake and its retry without losing the card');
  await action('rate','again');await click('退出学习');await click('保存位置，回到今日');await page.reload();
  assert(await page.getByRole('button',{name:'继续上次学习',exact:true}).count()===1,'Interrupted session is offered after reload');
  await click('词库');await click('今日');await click('继续上次学习');
  assert(await page.getByRole('heading',{name:'point',exact:true}).count()===1,'Browsing other pages does not erase the saved position');
  for(let i=0;i<4;i++){await click('查看释义');await action('rate','good');}
  assert(await page.getByRole('heading',{name:'这一组，记住了。',exact:true}).count()===1,'Learning pauses after five practices for a short group');
  await click('测一测这组的拼写');s=await read();assert(s.session.kind==='spell'&&s.session.returnCards.index===6,'Batch spelling retains the paused meaning-learning position');
  const meaningStage=s.words.provide.stage,meaningDue=s.words.provide.due;
  await page.getByLabel('英文拼写').fill('  PROVIDE  ');await click('提交拼写');s=await read();
  assert(s.session.spell.correct&&s.history[Object.keys(s.history).sort().pop()].spellCorrect===1,'Spelling accepts case and surrounding whitespace');
  assert(s.words.provide.stage===meaningStage&&s.words.provide.due===meaningDue,'Spelling does not falsely raise meaning mastery or change its review date');
  await click('下一个单词');await page.getByLabel('英文拼写').fill('poit');await click('提交拼写');s=await read();
  assert(s.words.point.spellWeak&&s.words.point.spellErrors===1&&!s.words.point.meaningWeak,'Spelling errors are tracked separately from forgotten meaning');
  assert(await page.locator('.diff-missing').count()===1,'Letter feedback identifies the missing character');
  await page.screenshot({path:'output/playwright/v1.1-spelling.png'});
  await click('撤销上一次选择');s=await read();assert(!s.words.point.spellWeak&&s.words.point.spellErrors===0&&!s.session.spell.checked,'Undo also restores spelling errors and statistics');
  await click('提交拼写');await click('下一个单词');await click('首字母提示');await page.getByLabel('英文拼写').fill('follow');await click('提交拼写');s=await read();
  assert(s.words.follow.spellWeak&&s.words.follow.spellErrors===0,'A hinted correct answer remains weak without being counted as a spelling error');
  await click('下一个单词');await click('查看答案');await click('下一个单词');await page.getByLabel('英文拼写').fill('local');await click('提交拼写');await click('完成本轮拼写');
  await click('回到词义学习');assert(await page.getByRole('heading',{name:'provide',exact:true}).count()===1,'Spelling returns to the exact pending retry card');
  await click('查看释义');await action('rate','good');s=await read();let key=Object.keys(s.history).sort().pop();
  assert(s.history[key].new.length===5&&s.history[key].words.length===5&&s.history[key].attempts===11,'Meaning retries and spelling do not double-count five new words');
  assert(s.history[key].spellAttempts===5&&s.history[key].spellCorrect===2,'Independent spelling accuracy excludes hinted and revealed answers');
  assert(s.words.provide.meaningWeak&&s.words.provide.meaningWins===1,'Same-day improvement does not immediately remove meaning weakness');
  await click('回到今日');await action('weak-list');
  assert(await page.locator('.word-row').count()===5,'Reinforcement list contains legacy weakness plus distinct new meaning and spelling weak words');
  await page.screenshot({path:'output/playwright/v1.1-weak.png'});
  await action('spell-start','spellingWeak');let current=(await read()).session.queue[0];await page.getByLabel('英文拼写').fill('partial-answer');
  await click('退出学习');await click('保存位置，回到今日');await click('我的');
  const downloadPromise=page.waitForEvent('download');await action('export');const download=await downloadPromise;await download.saveAs('output/playwright/v1.1-backup.json');
  await page.getByLabel('每天的新词目标').selectOption('20');await page.locator('#backup-file').setInputFiles('output/playwright/v1.1-backup.json');
  assert(await page.getByRole('heading',{name:'恢复这份备份？',exact:true}).count()===1,'Backup restoration asks before overwriting current progress');
  await click('确认恢复');s=await read();assert(s.goal===5&&s.plan.ids.length===100&&s.words.system.known&&s.words.point.spellWeak,'Backup restores route, skips and separated weak states');
  await click('今日');await click('继续上次学习');assert(await page.getByLabel('英文拼写').inputValue()==='partial-answer','Backup preserves a partially typed spelling answer');
  // Place the recorded active time past the budget, without waiting five real minutes.
  await click('退出学习');await click('保存位置，回到今日');s=await read();s.history[key].activeMs=300001;await saveFixture(s);await click('继续上次学习');
  await page.getByLabel('英文拼写').fill(current);await click('提交拼写');await click('下一个单词');
  assert(await page.getByRole('heading',{name:'先休息一下。',exact:true}).count()===1,'Daily time budget produces a pause after completing the current word');
  await click('继续本轮学习');assert((await read()).session.budgetAt>300001,'Continuing explicitly extends the budget without erasing daily learning time');
  await click('退出学习');await click('保存位置，回到今日');
  // A single-word spelling session makes repeated-day reinforcement easy to inspect.
  s=await read();s.session=null;s.words[current].spellWeak=true;s.words[current].spellWins=0;s.words[current].spellWinDay='';
  for(const [w,p]of Object.entries(s.words))if(w!==current)p.spellWeak=false;
  await saveFixture(s);
  async function spellOnce(){await action('weak-list');await action('spell-start','spellingWeak');await page.getByLabel('英文拼写').fill(current);await click('提交拼写');await click('完成本轮拼写');await click('回到今日');}
  await spellOnce();await spellOnce();s=await read();assert(s.words[current].spellWeak&&s.words[current].spellWins===1,'Two correct attempts on the same date do not clear spelling weakness');
  const before=Date.now();await page.clock.install({time:new Date(before)});await page.clock.setFixedTime(new Date(before+86400000));
  await spellOnce();s=await read();assert(!s.words[current].spellWeak&&s.words[current].spellWins===2,'An independent correct answer on the next date clears spelling weakness');
  await page.clock.setFixedTime(new Date(before));
  await action('plan');await page.getByLabel('学习路线',{exact:true}).selectOption('custom');await page.getByLabel('本轮范围上限').selectOption('100');
  await page.locator('input[name="tiers"][value="common"]').uncheck();await page.locator('input[name="tiers"][value="extended"]').uncheck();await click('保存学习计划');s=await read();
  assert(s.plan.route==='custom'&&s.plan.ids.length===100&&s.plan.ids.every(w=>w!==undefined),'Custom route stores its chosen cohort');
  assert(await page.evaluate(()=>state.plan.ids.every(w=>WORD_MAP.get(w).tier==='intermediate')),'Custom intermediate route excludes other tiers');
  await click('开始今日学习');assert(await page.getByText('本词暂未配例句。',{exact:true}).count()===0,'Unrevealed card does not leak its explanation');
  await click('查看释义');assert(await page.getByText('本词暂未配例句。',{exact:true}).count()===1,'Missing example coverage is stated clearly');
  await click('退出学习');await click('保存位置，回到今日');
  await action('plan');await page.getByLabel('学习路线',{exact:true}).selectOption('complete');await click('保存学习计划');assert((await read()).plan.ids.length===5406,'Complete route restores the entire vocabulary without deleting progress');
  assert(await page.evaluate(()=>accepted('centre','center')&&!accepted('centre','central')),'Explicit spelling variants accept center but reject a different word');
  await click('词库');await click('全部');await page.getByLabel('学习范围筛选').selectOption('extended');
  assert((await page.locator('#result-count').innerText()).includes('1906'),'Dictionary tier filtering reflects the actual extended cohort size');
  await page.setViewportSize({width:320,height:740});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Dictionary has no horizontal overflow at 320 pixels');
  await click('今日');assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Home has no horizontal overflow at 320 pixels');
  await action('plan');assert(await page.evaluate(()=>document.querySelector('.modal').scrollWidth<=document.querySelector('.modal').clientWidth),'Plan dialog fits a narrow screen');await click('关闭');
  assert(errors.length===0,'Complete upgrade workflow produces no JavaScript errors');
  // Leave a clean, focused preview. Reload before clearing avoids pagehide saving the fixture again.
  await page.reload();await page.evaluate(()=>{study=null;state=fresh();localStorage.removeItem('wordleaf-state');});await page.reload();await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:'output/playwright/v1.1-home.png'});
  assert(await page.evaluate(()=>{study=session('spell','spell',['government']);page='spell';renderSpelling();const text=document.querySelector('.spell-hint').textContent;return text.includes('10')&&!text.includes('${');}),'Spelling prompt renders the actual reference length without a template fragment');
  await page.evaluate(()=>{study=null;state.session=null;page='home';render();save();});
  return{passed:checks.length,checks};
}
