async(page)=>{
  const checks=[],errors=[];page.on('pageerror',e=>errors.push(e.message));
  const assert=(ok,label)=>{if(!ok)throw Error(label);checks.push(label);};
  const action=(name,id)=>page.locator(`[data-action="${name}"]${id?'[data-id="'+id+'"]':''}`).first().click();
  const click=name=>page.getByRole('button',{name,exact:true}).click();
  const read=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('wordleaf-state')));
  const seed=async(data)=>{await page.goto('http://127.0.0.1:8765/qa-blank');await page.evaluate(data=>localStorage.setItem('wordleaf-state',JSON.stringify(data)),data);await page.goto('http://127.0.0.1:8765/');};
  await page.goto('http://127.0.0.1:8765/');await page.setViewportSize({width:390,height:844});
  const legacy=await page.evaluate(()=>{useBook('cet6');const s=fresh();s.plan.size=600;s.plan.ids=WORDS.slice(0,600).map(w=>w.w);s.planChosen=true;s.words.government={...emptyProgress(),stage:2,reps:3,star:true,first:dayKey(),due:Date.now()+DAY};s.session=session('cards','daily',['system','provide']);s.session.revealed=true;return s;});
  await seed(legacy);
  assert(await page.evaluate(()=>activeMode==='cet6'&&state.words.government.stage===2&&state.words.government.star&&state.plan.ids.length===600),'1.1 upgrade keeps the CET-6 plan, mastery and favorite');
  assert(await page.evaluate(()=>state.session.queue[0]==='system'&&state.session.revealed),'Upgrade preserves the exact unfinished learning position');
  await action('mode');assert(await page.getByRole('dialog',{name:'选择学习模式'}).count()===1,'Home badge opens a labeled mode picker');
  assert(await page.locator('.mode-option').count()===3,'All three real learning modes are offered');
  await page.screenshot({path:'output/playwright/v1.2-modes.png'});
  await action('switch-mode','cet6');assert(await page.getByRole('dialog').count()===0,'Selecting the active mode closes the picker without changing progress');
  await action('mode');await action('switch-mode','cet4');
  assert(await page.evaluate(()=>WORDS.length===3846&&DATASET==='ecdict-cet4-v1'&&activeMode==='cet4'),'CET-4 loads its own vocabulary rather than renaming CET-6');
  assert(await page.evaluate(()=>!state.words.government&&state.session===null),'New mode starts independently of existing CET-6 records');
  await action('plan');await page.getByLabel('本轮范围上限').selectOption('600');await page.getByLabel('计划每日新词目标').selectOption('10');await page.getByLabel('备考天数',{exact:true}).fill('21');await click('保存学习计划');
  await click('开始今日学习');await click('查看释义');await page.getByRole('button',{name:'有点模糊 1 天后',exact:true}).click();
  await click('退出学习');await click('保存位置，回到今日');
  assert(await page.evaluate(()=>state.words.government.meaningWeak&&state.session.index===1),'CET-4 records meaning weakness and saves its next card');
  await page.evaluate(()=>{const cards=clone(state.session),s=session('spell','batch',['government']);s.returnCards=cards;openSession(s);persistSession();});
  await page.getByLabel('英文拼写').fill('gover');await click('退出学习');await click('保存位置，回到今日');
  await action('mode');await action('switch-mode','daily');
  assert(await page.evaluate(()=>WORDS.length===1000&&WORDS[0].w==='the'&&MEANINGS.the.startsWith('art.')),'Daily mode provides common vocabulary including basic words and Chinese meanings');
  assert(await page.getByRole('button',{name:'切换学习模式，当前 日常学习'}).count()===1,'Current mode is visible in the home badge');
  await action('plan');
  assert(await page.getByLabel('本轮范围上限').locator('option[value="3500"]').count()===0,'Daily plan cannot select a range larger than its word book');
  assert(await page.locator('input[name="tiers"][value="extended"]').isDisabled(),'Empty vocabulary tiers are disabled');
  await click('保存学习计划');assert(await page.evaluate(()=>state.plan.tiers.length===1&&state.plan.tiers[0]==='common'),'Daily plan saves only available vocabulary tiers');
  await click('开始今日学习');await click('查看释义');assert((await page.locator('.definition').innerText()).includes('art. 这'),'Daily learning cards show the actual basic Chinese meaning');
  await action('known','the');await click('退出学习');await click('保存位置，回到今日');
  assert(await page.evaluate(()=>state.words.the.known&&today().new.length===0),'Known-word skipping works in the daily book');
  await action('mode');await action('switch-mode','cet4');
  assert(await page.evaluate(()=>state.goal===10&&state.plan.days===21&&state.plan.ids.length===600),'Switching back restores the CET-4 settings');
  assert(await page.evaluate(()=>state.session.kind==='spell'&&state.session.spell.answer==='gover'&&state.session.returnCards.index===1),'Switching modes preserves partial spelling input and its return card');
  await page.reload();assert(await page.evaluate(()=>activeMode==='cet4'&&state.session.spell.answer==='gover'),'A cold reload restores the selected mode and unfinished spelling');
  await click('继续上次学习');assert(await page.getByLabel('英文拼写').inputValue()==='gover','Resume restores the typed answer in the input');
  await click('退出学习');await click('保存位置，回到今日');
  await action('mode');await action('switch-mode','cet6');
  assert(await page.evaluate(()=>state.words.government.stage===2&&!state.words.government.meaningWeak&&state.words.government.star),'CET-4 practice did not overwrite CET-6 progress');
  assert(await page.evaluate(()=>state.session.kind==='cards'&&state.session.queue[0]==='system'&&state.session.revealed),'CET-6 resumes its original revealed card');
  await click('继续上次学习');assert(await page.getByRole('heading',{name:'system',exact:true}).count()===1,'CET-6 resume displays the saved target word');
  await click('退出学习');await click('保存位置，回到今日');await click('我的');
  const downloadPromise=page.waitForEvent('download');await action('export');const download=await downloadPromise;await download.saveAs('output/playwright/v1.2-backup.json');
  const backup=await read();assert(backup.version===3&&Object.keys(backup.books).length===3,'Backup includes all three mode profiles');
  assert(backup.books.daily.words.the.known&&backup.books.cet4.session.spell.answer==='gover','Backup contains inactive progress and partial spelling');
  await page.getByLabel('每天的新词目标').selectOption('50');await page.locator('#backup-file').setInputFiles('output/playwright/v1.2-backup.json');
  await page.getByText('恢复这份备份？',{exact:true}).waitFor({state:'visible'});
  assert(await page.getByText('恢复这份备份？',{exact:true}).count()===1,'Multi-mode backup restoration requests confirmation');
  assert((await page.getByRole('dialog').innerText()).includes('所有模式'),'Restore clearly states that all mode records will be replaced');
  await click('确认恢复');assert(await page.evaluate(()=>activeMode==='cet6'&&state.goal===20&&library.books.cet4.goal===10&&library.books.daily.words.the.known),'Restore reinstates every book with its own settings');
  const invalid=JSON.parse(JSON.stringify(backup));invalid.books.daily.words.unknown={...invalid.books.cet6.words.government};
  await page.evaluate(data=>window.receiveBackup(JSON.stringify(data)),invalid);
  assert(await page.getByRole('dialog').count()===0,'Invalid data in an inactive profile is rejected before confirmation');
  assert(await page.evaluate(()=>activeMode==='cet6'&&DATASET==='ecdict-cet6-v1'&&state.words.government.stage===2),'Failed import leaves the active vocabulary and progress unchanged');
  await action('mode');await action('switch-mode','daily');await page.evaluate(data=>window.receiveBackup(JSON.stringify(data)),legacy);await click('确认恢复');
  assert(await page.evaluate(()=>activeMode==='cet6'&&Object.keys(library.books).length===1&&state.plan.ids.length===600),'An old single-book backup restores to CET-6 even when imported from daily mode');
  await seed(backup);await page.getByRole('button',{name:'今日',exact:true}).click();
  const touch=await page.evaluate(()=>{const target=document.querySelector('.mode-trigger');const one=new Touch({identifier:1,target,clientX:100,clientY:50}),two=new Touch({identifier:2,target,clientX:200,clientY:50});const single=new TouchEvent('touchstart',{touches:[one],bubbles:true,cancelable:true});const start=new TouchEvent('touchstart',{touches:[one,two],bubbles:true,cancelable:true});const move=new TouchEvent('touchmove',{touches:[one,two],bubbles:true,cancelable:true});target.dispatchEvent(single);target.dispatchEvent(start);target.dispatchEvent(move);return{single:single.defaultPrevented,multiStart:start.defaultPrevented,multiMove:move.defaultPrevented,viewport:document.querySelector('meta[name="viewport"]').content,touchAction:getComputedStyle(document.documentElement).touchAction};});
  assert(!touch.single&&touch.multiStart&&touch.multiMove,'Multi-touch zoom is canceled while single-touch input stays enabled');
  assert(touch.viewport.includes('maximum-scale=1')&&touch.viewport.includes('user-scalable=no')&&touch.touchAction==='pan-y','Viewport and CSS disable page zoom while allowing vertical pan');
  const cdp=await page.context().newCDPSession(page);await cdp.send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});await cdp.send('Emulation.setTouchEmulationEnabled',{enabled:true,maxTouchPoints:2});
  await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:150,y:300,id:1},{x:210,y:300,id:2}]});
  await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:100,y:300,id:1},{x:260,y:300,id:2}]});
  await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:70,y:300,id:1},{x:290,y:300,id:2}]});
  await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
  assert(await page.evaluate(()=>Math.abs(visualViewport.scale-1)<.01),'A real browser pinch gesture does not enlarge the page');
  await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:180,y:650,id:3}]});
  await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:180,y:550,id:3}]});
  await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:180,y:450,id:3}]});
  await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:180,y:350,id:3}]});
  await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
  assert(await page.evaluate(()=>scrollY>0),'Single-finger touch scrolling still works');
  await cdp.send('Emulation.clearDeviceMetricsOverride');await cdp.detach();
  await page.setViewportSize({width:320,height:740});await action('mode');
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth&&document.querySelector('.modal').scrollWidth<=document.querySelector('.modal').clientWidth),'Mode picker fits a narrow phone without horizontal overflow');
  await action('switch-mode','daily');await action('plan');
  assert((await page.locator('#plan-preview').innerText()).includes('本轮 300 词'),'Daily plan preview uses the actual chosen range');await click('关闭');
  await click('词库');assert((await page.locator('#result-count').innerText()).includes('1000'),'Daily dictionary counts its own 1,000 entries');
  await page.getByLabel('搜索单词或中文释义').fill('一个');assert(await page.locator('.word-row').count()>0,'Chinese search uses the daily meanings');
  assert(await page.evaluate(()=>Object.values(BOOKS).every(b=>b.words.every(w=>!own(w,'t')&&!own(w,'d')&&b.meanings[w.w]))),'Every mode ships focused Chinese meanings without full or English glosses');
  assert(errors.length===0,'Mode and gesture workflows have no JavaScript errors');
  await seed(backup);await action('mode');await action('switch-mode','daily');await page.setViewportSize({width:390,height:844});await page.screenshot({path:'output/playwright/v1.2-daily.png'});
  await page.evaluate(()=>{stopTick();useBook('cet6');library={version:3,activeMode:'cet6',books:{}};state=fresh();study=null;modal=null;page='home';save();render();});await page.reload();await page.screenshot({path:'output/playwright/v1.2-home.png'});
  return{passed:checks.length,checks};
}
