async(page)=>{
 const checks=[],errors=[];page.on('pageerror',e=>errors.push(e.message));
 const assert=(ok,label)=>{if(!ok)throw Error(label);checks.push(label);};
 await page.goto('http://127.0.0.1:8765/');await page.setViewportSize({width:390,height:844});
 const original=await page.evaluate(()=>{const s=fresh();s.planChosen=true;s.goal=5;s.words.program={...emptyProgress(),reps:2,stage:2,star:true,meaningWeak:true,lapses:1,due:123456,first:'2026-10-01'};s.words.government={...emptyProgress(),known:true};const w=WORDS.find(w=>!['program','government'].includes(w.w)).w;s.history[dayKey()]={...emptyHistory(),words:[w],new:[w],attempts:1,newTarget:5};s.words[w]={...emptyProgress(),reps:1,stage:1,due:Date.now()+DAY,first:dayKey()};return{version:3,activeMode:'cet6',books:{cet6:s}};});
 await page.goto('http://127.0.0.1:8765/qa-blank');await page.evaluate(d=>localStorage.setItem('wordleaf-state',JSON.stringify(d)),original);await page.goto('http://127.0.0.1:8765/');
 await page.getByRole('button',{name:'我的',exact:true}).click();await page.locator('[data-action=collections]').click();
 const fixture=await page.evaluate(()=>{const base=BOOKS.cet6.words.filter(w=>!['program','government','CORE'].includes(w.w));const ids=['program','government',...base.slice(0,1985).map(w=>w.w)];const extra=['serve','core',...Array.from({length:526},(_,i)=>'fixture'+String.fromCharCode(97+Math.floor(i/26))+String.fromCharCode(97+i%26))];return{format:'wordleaf-wordlist-v1',name:'测试核心词库',source:'Synthetic collection used only for testing.',entries:[...ids.map(word=>({word})),...extra.map(word=>({word,phonetic:'',meaning:'n. 测试词条'}))]};});
 await page.locator('#wordlist-file').setInputFiles({name:'test-collection.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(fixture))});
 assert(await page.evaluate(()=>modal.type==='collection-import'&&modal.draft.collection.ids.length===2515),'A 2,515-word synthetic list loads as a preview');
 assert(await page.evaluate(()=>state.collection===null&&state.activeList==='base'),'Preview does not change existing data');
 await page.locator('[data-action=collection-confirm]').click();
 assert(await page.evaluate(()=>state.activeList==='custom'&&pool().length===2515),'Import activates the full selected collection');
 assert(await page.evaluate(()=>state.collection.ids[0]==='program'&&state.customEntries.length===528),'Exact ordinary spellings reuse records and add 528 entries, preserving acronym distinctions');
 assert(await page.evaluate(()=>progress('program').reps===2&&progress('program').due===123456&&progress('program').star&&progress('program').meaningWeak),'Shared words retain mastery, due time, favorite and mistakes');
 assert(await page.evaluate(()=>progress('government').known&&!newWords().some(w=>w.w==='program'||w.w==='government')),'Learned and known words are excluded from new words');
 assert(await page.evaluate(()=>today().newTarget===5&&today().new.length===1&&remaining()===4),'Switching books preserves the locked daily goal and completed count');
 assert(await page.evaluate(()=>shortMeaning(WORD_MAP.get('serve')).length<=180&&WORD_MAP.has('core')),'New entries have concise Chinese meanings and missing dictionary fallback');
 await page.reload();assert(await page.evaluate(()=>!readFailed&&state.collection.ids.length===2515&&WORD_MAP.has('serve')),'Cold reload restores imported entries, selected book and records');
 const backup=await page.evaluate(()=>clone(snapshotLibrary()));
 assert(await page.evaluate(d=>validateLibrary(d).books.cet6.collection.ids.length===2515,backup),'Backup validation includes all imported words');
 await page.evaluate(()=>{state.words.serve={...emptyProgress(),reps:1,stage:1,due:456789,first:dayKey()};save();selectCollection('base');});
 assert(await page.evaluate(()=>availableWords().length===5406&&progress('serve').reps===1&&today().newTarget===5),'Returning to the original book retains imported-only word progress');
 assert(await page.evaluate(()=>state.plan.ids.length===300),'Returning to the original book restores its previous learning range');
 await page.evaluate(()=>selectCollection('custom'));assert(await page.evaluate(()=>pool().length===2515&&progress('serve').due===456789),'Returning to the imported book restores the same progress');
 await page.evaluate(()=>switchMode('cet4'));assert(await page.evaluate(()=>!state.collection&&!WORD_MAP.has('core')||activeMode==='cet4'&&WORDS.length===3846),'CET-4 data remains separate');
 await page.evaluate(()=>switchMode('cet6'));assert(await page.evaluate(()=>state.collection.ids.length===2515&&progress('serve').reps===1),'Mode switching restores the imported CET-6 catalog');
 await page.evaluate(()=>{startStudy('new',true);});assert(await page.evaluate(()=>study.queue.every(w=>state.collection.ids.includes(w)&&!progress(w).reps&&!progress(w).known)),'New-word study uses only unlearned words from the selected book');
 await page.evaluate(()=>{study.revealed=true;rate('good');});assert(await page.evaluate(()=>today().new.length===2&&today().newTarget===5),'Learning imported words updates the existing daily task once');
 await page.evaluate(()=>undo());assert(await page.evaluate(()=>today().new.length===1&&today().newTarget===5),'Undo restores imported-word daily statistics');
 await page.reload();assert(await page.evaluate(()=>!readFailed&&state.session.kind==='cards'&&state.session.queue.every(w=>state.collection.ids.includes(w))),'Unfinished imported-word session survives reload');
 await page.evaluate(()=>{page='stats';render();receiveWordlist(JSON.stringify({format:'wordleaf-wordlist-v1',name:'测试',source:'测试',entries:[{word:'program'},{word:'PROGRAM'},{word:'government'}]}));});
 assert(await page.evaluate(()=>modal.draft.collection.ids.length===2),'Case differences and repeated spellings map to a single stable word');
 await page.locator('[data-action=close]').first().click();const before=await page.evaluate(()=>JSON.stringify(state));
 await page.evaluate(()=>receiveWordlist(JSON.stringify({format:'wordleaf-wordlist-v1',name:'错误',source:'测试',entries:[{word:'<script>bad</script>'}]})));
 assert(await page.evaluate(()=>JSON.stringify(state))===before,'Invalid imported words do not mutate learning records');
 assert(await page.evaluate(()=>{const d=clone(snapshotLibrary());d.books.cet6.collection.ids.push('missingword');try{validateLibrary(d);return false;}catch(e){return WORD_MAP.has('serve')&&activeMode==='cet6';}}),'Invalid collection backup is rejected without changing active catalog');
 await page.evaluate(()=>{receiveWordlist(JSON.stringify({format:'wordleaf-wordlist-v1',name:'<b>名称</b>',source:'<script>来源</script>',entries:[{word:'program'}]}));});
 assert(await page.locator('.modal h2 b').count()===0&&await page.locator('.modal script').count()===0,'Imported labels and source text are escaped');
 await page.locator('[data-action=close]').first().click();await page.evaluate(()=>{study=null;state.session=null;selectCollection('base');});
 assert(await page.evaluate(()=>progress('serve').reps===1&&state.customEntries.length===528),'Replacing or changing a list never deletes earlier imported word records');
 await page.setViewportSize({width:320,height:844});await page.getByRole('button',{name:'我的',exact:true}).click();await page.locator('[data-action=collections]').click();
 assert(await page.evaluate(()=>document.querySelector('.modal').scrollWidth<=document.querySelector('.modal').clientWidth),'Collection picker fits a 320-pixel phone');
 await page.screenshot({path:'output/playwright/v1.3.3-collections.png'});
 assert(errors.length===0,'No browser runtime errors');return{passed:checks.length,checks};
}
