async(page)=>{
  const checks=[],errors=[];
  page.on('pageerror',e=>errors.push(e.message));
  const assert=(ok,label)=>{if(!ok)throw Error(label);checks.push(label);};
  const click=name=>page.getByRole('button',{name,exact:true}).click();
  const action=(name,id)=>page.locator(`[data-action="${name}"]${id?'[data-id="'+id+'"]':''}`).first().click();
  const seed=async(data)=>{await page.goto('http://127.0.0.1:8765/qa-blank');await page.evaluate(data=>localStorage.setItem('wordleaf-state',JSON.stringify(data)),data);await page.goto('http://127.0.0.1:8765/');};
  const learn=async(rating='good')=>{await click('查看释义');await action('rate',rating);};
  const total=()=>page.evaluate(()=>learningDays().size);
  await page.clock.setFixedTime(new Date('2026-10-01T12:00:00'));
  await page.goto('http://127.0.0.1:8765/');await page.setViewportSize({width:390,height:844});
  const fixture=await page.evaluate(()=>{
    useBook('cet6');const s=fresh();s.goal=5;s.planChosen=true;
    let offset=500;
    function history(date,n,target){const list=WORDS.slice(offset,offset+n).map(w=>w.w);offset+=n;for(const w of list)s.words[w]={...emptyProgress(),reps:1,stage:1,first:date,due:Date.now()+30*DAY};s.history[date]={...emptyHistory(),words:list,new:list,attempts:n};if(target!=null)s.history[date].newTarget=target;else delete s.history[date].newTarget;}
    history('2026-09-26',20,null);history('2026-09-28',3,5);history('2026-09-29',5,5);history('2026-09-30',5,5);
    return{version:3,activeMode:'cet6',books:{cet6:s}};
  });
  await seed(fixture);await click('我的');
  assert(await total()===2,'Legacy practice without a stored goal and partial new-word days do not count as completed learning days');
  assert(await page.evaluate(()=>streak()===2&&longestStreak(learningDays())===2),'Streak continues from yesterday until today is completed');
  assert(await page.locator('.bar-item').count()===7,'Recent seven-day practice chart is retained');
  await click('上个月');
  assert(await page.locator('.calendar-day.complete').count()===2,'Calendar shows the actual completed dates from the previous month');
  assert(await page.locator('[aria-label="2026-09-26，有练习，未记录达标"]').count()===1,'Old practice is displayed without inventing historical check-ins');
  await page.screenshot({path:'output/playwright/v1.3.1-history.png'});await click('下个月');
  assert(await page.getByRole('button',{name:'下个月',exact:true}).isDisabled(),'Calendar cannot navigate into a future month');
  await click('今日');await action('start','new');
  assert(await page.evaluate(()=>today().newTarget===5&&today().new.length===0&&!completedDay(today())),'Starting new-word learning locks the goal without granting a check-in');
  await click('这个词我已会，跳过');
  assert(await total()===2&&await page.evaluate(()=>today().new.length===0),'Skipping a known word never counts as learning a new word or completing a day');
  await click('撤销上一次选择');await learn();
  await click('退出学习');await click('保存位置，回到今日');await click('我的');
  await page.getByLabel('每天的新词目标').selectOption('20');
  assert(await page.evaluate(()=>state.goal===20&&dailyGoal()===5&&today().newTarget===5),'Changing the configured goal preserves the locked goal for today');
  await action('plan');await page.getByLabel('计划每日新词目标').selectOption('10');await click('保存学习计划');
  assert(await page.evaluate(()=>state.goal===10&&dailyGoal()===5&&today().new.length===1),'Changing the learning plan does not lower or reset the daily completion requirement');
  await action('start','new');
  assert(await page.evaluate(()=>study.queue.length===4),'Learning queue uses the remaining locked quota after a settings or scope change');
  await learn('again');
  assert(await page.evaluate(()=>today().new.length===2&&today().attempts===2&&!completedDay(today())),'A completed new-word attempt is recorded, but partial completion does not check in');
  for(let i=0;i<3;i++)await learn();
  assert(await total()===3&&await page.evaluate(()=>completedDay(today())&&streak()===3),'Only finishing the locked new-word target completes the day');
  assert((await page.locator('#toast').innerText()).includes('学习打卡已点亮'),'Completing the goal shows an automatic check-in notice');
  await click('撤销上一次选择');
  assert(await total()===2&&await page.evaluate(()=>!completedDay(today())&&today().new.length===4),'Undo of the completing attempt also removes the check-in');
  await action('rate','good');
  assert(await total()===3,'Re-completing an undone word restores one check-in without duplication');
  await learn();
  assert(await page.evaluate(()=>today().new.length===5&&learningDays().size===3),'A same-session meaning retry does not inflate new-word counts or learning days');
  await click('测一测这组的拼写');
  const queue=await page.evaluate(()=>study.queue.slice());
  for(let i=0;i<queue.length;i++){await page.getByLabel('英文拼写').fill(queue[i]);await click('提交拼写');await click(i+1<queue.length?'下一个单词':'完成本轮拼写');}
  assert(await total()===3&&await page.evaluate(()=>today().new.length===5),'Spelling practice adds neither new words nor additional learning days');
  await click('回到词义学习');await click('回到今日');await click('我的');
  assert(await page.locator('.calendar-day.today.complete').count()===1,'Today lights up in the learning calendar after completion');
  await page.evaluate(()=>document.getElementById('toast').classList.remove('visible'));
  await page.screenshot({path:'output/playwright/v1.3.1-checkin.png',fullPage:true});
  const download=page.waitForEvent('download');await action('export');await(await download).saveAs('output/playwright/v1.3.1-backup.json');
  await page.evaluate(()=>{state.history={};save();});
  await page.locator('#backup-file').setInputFiles('output/playwright/v1.3.1-backup.json');await page.getByRole('heading',{name:'恢复这份备份？',exact:true}).waitFor({state:'visible'});await click('确认恢复');await page.reload();
  assert(await total()===3&&await page.evaluate(()=>today().newTarget===5&&today().new.length===5),'Backup and cold reload preserve locked targets and completed learning days');
  await action('mode');await action('switch-mode','cet4');await click('我的');await page.getByLabel('每天的新词目标').selectOption('5');await click('今日');await action('start','new');
  for(let i=0;i<5;i++)await learn();await click('回到今日');
  assert(await total()===3&&await page.evaluate(()=>completedDay(today())),'Completing a second vocabulary mode on the same date still counts only one learning day');
  await action('mode');await action('switch-mode','cet6');
  await page.clock.setFixedTime(new Date('2026-10-02T12:00:00'));await page.reload();await action('start','new');
  assert(await page.evaluate(()=>today().newTarget===10&&study.queue.filter(w=>!progress(w).reps).length===10),'The changed new-word goal takes effect on the following date');
  await learn();
  assert(await total()===3&&await page.evaluate(()=>streak()===3&&!completedDay(today())),'A partial day keeps the previous streak visible without increasing completed days');
  await click('退出学习');await click('保存位置，回到今日');
  await page.clock.setFixedTime(new Date('2026-10-04T12:00:00'));await page.reload();
  assert(await page.evaluate(()=>streak()===0&&longestStreak(learningDays())===3),'Missing a completion day resets the current streak but preserves its historical maximum');
  await click('我的');
  for(const width of [320,360,390]){await page.setViewportSize({width,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth&&document.querySelector('.checkin-calendar').scrollWidth<=document.querySelector('.checkin-calendar').clientWidth),'Learning calendar fits width '+width);}
  const invalid=await page.evaluate(()=>{const data=clone(snapshotLibrary());data.books.cet6.history['2026-10-01'].newTarget=0;try{validateLibrary(data);return false}catch(e){return true}});
  assert(invalid,'Invalid saved check-in targets are rejected during backup validation');
  const reviewOnly=await page.evaluate(()=>{const s=fresh();s.planChosen=true;s.goal=5;s.words.government={...emptyProgress(),reps:1,stage:1,first:'2026-10-01',due:1};return{version:3,activeMode:'cet6',books:{cet6:s}};});
  await seed(reviewOnly);await action('start','review');await learn();await click('回到今日');
  assert(await total()===0&&await page.evaluate(()=>today().words.length===1&&today().new.length===0),'A review-only day appears as practice and never counts as a new-word completion day');
  const tail=await page.evaluate(()=>{const s=fresh();s.planChosen=true;s.goal=20;s.plan.size=2;s.plan.ids=WORDS.slice(0,2).map(w=>w.w);return{version:3,activeMode:'cet6',books:{cet6:s}};});
  await seed(tail);await action('start','new');
  assert(await page.evaluate(()=>today().newTarget===2),'When fewer new words remain than the configured goal, the actual starting task is locked');
  await learn();await learn();await click('回到今日');
  assert(await total()===1,'Completing the last remaining words completes the assigned learning day');
  await page.clock.setFixedTime(new Date('2026-10-05T12:00:00'));await page.clock.runFor(30001);
  assert(await page.getByRole('button',{name:'完成当天新词任务，自动打卡',exact:true}).count()===1,'Home refreshes the check-in status after a foreground date rollover');
  await click('我的');await page.clock.setFixedTime(new Date('2026-10-06T12:00:00'));await page.clock.runFor(30001);
  assert(await page.locator('[aria-current="date"][aria-label^="2026-10-06"]').count()===1,'The visible learning calendar refreshes its current date automatically');
  assert(errors.length===0,'Check-in, migration, calendar and backup workflows have no browser runtime errors');
  return{passed:checks.length,checks};
}
